### ISSUE TITLE
Regarding the license used in the current release 1.0.5

### ISSUE THREAD

**Issue by etman** [shevek/lzo-java#9]
Hi, I've seen the lzo-core is released under Apache-2.0 license in the resulting maven POM file. However, the LICENSE file states the library is released under GNU GPL v3. So I would like to ask what license the current version(1.0.5) actually uses?

**Comment by wesc** [comment]
Clarification on this would be great. It's controversial, but according to the FSF (which maintains the copyright of the GPL text), _any_ program that ships with lzop support using this library must be entirely GPL. Basically none of Hadoop is GPL, so this is problematic. I would assume that the license listed in this source repo is the truth since it's bundled with the code, and that the Maven POM is incorrect.

**Comment by shevek** [comment]
Yes, as this is based on the actual lzop code, it must be GPL. I will fix the POM file.

**Comment by shevek** [comment]
Will be fixed on next release.
